# Creating Array

In [1]:
import numpy as np

In [2]:
a=np.array([3,5,6,1,8])

In [4]:
b=np.array([(1,6,9),(3,7,2)],dtype=float)

In [6]:
c=np.array([(1,6,9),(7,2,1),(3,7,2)],dtype=float)

# Initial Placeholders

In [8]:
#creating an array of zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
#creating an array of once
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
#creating an array of evenly distributed value
np.arange(10,25,5)

array([10, 15, 20])

In [11]:
#creating an array of evenly spaced value
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [12]:
#creating a constant array
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [13]:
#creating identity matrix
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

In [20]:
#creating array with random value
import random
np.random.random((2,2))

array([[0.57590358, 0.31686348],
       [0.61505092, 0.89706369]])

# Input/Output

In [22]:
#saving and loading on the disk
np.save('my_array',a)
np.savez('my_Array',a,b)
np.load('my_array.npy')

array([3, 5, 6, 1, 8])

In [25]:
#saving and loading text files
np.loadtxt('myfile.txt')
np.genfromtxt('myfile.txt',delimiter=',')
np.savetxt('myfile.txt',a,delimiter=" ")

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:2: UserWarning: loadtxt: Empty input file: "myfile.txt"
  
/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:3: UserWarning: genfromtxt: Empty input file: "myfile.txt"
  This is separate from the ipykernel package so we can avoid doing imports until


# Datatypes

In [29]:
np.int64

np.float32
np.complex
np.bool
np.object
np.string_
np.unicode

str

# Inspecting Your Array

In [31]:
#array dimension
a.shape

(5,)

In [32]:
#array length
len(a)

5

In [34]:
#number of array dimensions
b.ndim

2

In [35]:
#size of array
c.size

9

In [36]:
#datatype
b.dtype

dtype('float64')

In [37]:
#name of dataype
c.dtype.name

'float64'

In [38]:
#converting into another type
c.astype('int')

array([[1, 6, 9],
       [7, 2, 1],
       [3, 7, 2]])

# Asking for help

In [40]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


# Arthimatic Operations

In [46]:
#addition
x=np.array([1,2,3])
y=np.array([9,8,7])
np.add(y,x)

array([10, 10, 10])

In [47]:
#subtracion
np.subtract(x,y)

array([-8, -6, -4])

In [49]:
#multipliction
np.multiply(x,y)

array([ 9, 16, 21])

In [50]:
#divsion
np.divide(x,2)

array([0.5, 1. , 1.5])

In [51]:
#exponential
np.exp(a)

array([2.00855369e+01, 1.48413159e+02, 4.03428793e+02, 2.71828183e+00,
       2.98095799e+03])

In [52]:
#square root
np.sqrt(a)

array([1.73205081, 2.23606798, 2.44948974, 1.        , 2.82842712])

In [53]:
#sin
np.sin(a)

array([ 0.14112001, -0.95892427, -0.2794155 ,  0.84147098,  0.98935825])

In [54]:
#cos
np.cos(a)

array([-0.9899925 ,  0.28366219,  0.96017029,  0.54030231, -0.14550003])

In [55]:
#log
np.log(a)

array([1.09861229, 1.60943791, 1.79175947, 0.        , 2.07944154])

In [56]:
#dot prduct
x.dot(y)

46

# Comparison


In [57]:
#element wise comparison
p=2
o=7
p==o

False

In [58]:
s=9
t=9
s==t

True

In [59]:
#array wise comparison
np.array_equal(x,y)

False

# Aggregate Function


In [60]:
#array wise sum
a.sum()

23

In [64]:
#minimum
a.min()


1

In [66]:
#maximum
b.max(axis=0)

array([3., 7., 9.])

In [67]:
#cumulative sum
b.cumsum(axis=1)

array([[ 1.,  7., 16.],
       [ 3., 10., 12.]])

In [68]:
#mean
a.mean()

4.6

In [70]:
#median
np.median(a)

5.0

In [72]:
#corelaton cofficient
np.corrcoef(b)

array([[ 1.        , -0.04676098],
       [-0.04676098,  1.        ]])

In [73]:
#standard deviation
np.std(b)

2.8674417556808756

# Subsetting, Slicing, Indexing

In [74]:
#sub setting
a[2]

6

In [76]:
b[1,2]

2.0

In [78]:
#slicing
a[1:2]

array([5])

In [79]:
b[0:2,1]

array([6., 7.])

In [80]:
b[:1]

array([[1., 6., 9.]])

In [82]:
c[1,...]

array([7., 2., 1.])

In [83]:
a[::-1]

array([8, 1, 6, 5, 3])

In [85]:
#boolean indexing
a[a<2]

array([1])

In [86]:
#fancy indexing
b[[1, 0, 1, 0]][:,[0,1,2,0]]

array([[3., 7., 2., 3.],
       [1., 6., 9., 1.],
       [3., 7., 2., 3.],
       [1., 6., 9., 1.]])

# Array Manipulation

In [87]:
#transposing array
i=np.transpose(a)

In [88]:
a.T

array([3, 5, 6, 1, 8])

In [89]:
#changing array shape
b.ravel()

array([1., 6., 9., 3., 7., 2.])

In [94]:
#adding removing element
a.resize((1,5))#resize
a

array([[3, 5, 6, 1, 8]])

In [96]:

np.append(x,y)#appending element


array([1, 2, 3, 9, 8, 7])

In [98]:
np.insert(a,1,5)#inserting element

array([3, 5, 5, 6, 1, 8])

In [101]:
np.delete(a,[5])#delete element

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: in the future out of bounds indices will raise an error instead of being ignored by `numpy.delete`.
  """Entry point for launching an IPython kernel.


array([3, 5, 6, 1, 8])

In [105]:
#combining array
np.concatenate((x,y),axis=0)

array([1, 2, 3, 9, 8, 7])

In [106]:
np.vstack((x,y))#vertical stacking

array([[1, 2, 3],
       [9, 8, 7]])

In [107]:
np.hstack((x,y))#horizntal stacking

array([1, 2, 3, 9, 8, 7])

In [109]:
np.column_stack((x,y))#column wise stacking

array([[1, 9],
       [2, 8],
       [3, 7]])

In [113]:
#spliting array
np.hsplit(x,3)#horizontally spliting

[array([1]), array([2]), array([3])]

In [116]:
np.vsplit(c,3)#vertically splitting

[array([[1., 6., 9.]]), array([[7., 2., 1.]]), array([[3., 7., 2.]])]